### ISSUE TITLE
Special Network Extension request no longer needed?

### ISSUE THREAD

**Issue by lazerwalker** [iCepa/iCepa#10]
Hey! I've been getting a dev environment set up — excited to potentially contribute to this project.

I shot off an email to Apple to get access to the proper Network Extension entitlement, and got this lovely autoreply email:

> Thank you for requesting information about the Network Extension framework. Please note that as of November 10, 2016 this process is not required for developers who wish to use App Proxy, Content Filter, or Packet Tunnel APIs. To use these services please navigate to your Developer Account at <https://developer.apple.com/account/> and select the Network Extension capability for the App ID you will be using for your app.
>
> If you are requesting an entitlement for Hotspot Helper APIs and have already filled out the request questionnaire then your request will be addressed at our earliest convenience. Otherwise please visit <https://developer.apple.com/contact/network-extension/> and enter the required information.

I assume this project is likely not using Network Extension framework APIs other than the Packet Tunnel APIs, and that thus manually emailing Apple might not be necessary any more to run on-device?

I still don't have a working dev environment (banging my head against Rust tun2tor issues — may open an issue here once it becomes obvious it isn't trivially user error), so I can't confirm yet, but this does seem promising. Figured I'd bring this to your attention, since it seems like such a recent policy change.

**Comment by chrisballinger** [comment]
Woah! Really? That's big news for people who might not be able to get the app via the App Store.

**Comment by conradev** [comment]
I missed this somehow – this is awesome! I updated the `README` to remove the part about emailing Apple.

I also updated the build instructions to be more complete. Are you still running into the `tun2tor` build issue? More than happy to help out if you are!

**Comment by conradev** [comment]
`iCepa` also has passing CI now as proof that compiling it is in fact possible 😜

**Comment by lazerwalker** [comment]
Gonna close this, since it seems pretty taken care of :)
