### ISSUE TITLE
Not Building 

### ISSUE THREAD

**Issue by Taherismail17** [iCepa/iCepa#11]
error: could not find `Cargo.toml` in `/Users/"myuser"/Downloads/iCepa-master/Extension/tun2tor` or any parent directory

I have completed all build steps

**Comment by conradev** [comment]
@Taherismail17 did you download the source tarball, or clone the repo? You will need to clone the repo in order to clone the project's submodules.

**Comment by Taherismail17** [comment]
Ok will try cloning, sorry I'm new to this, I'm 14 lol. So do you use git clone <URL> etc....

**Comment by Taherismail17** [comment]
I got the rest of it to work apart from this



Cloning into '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl'...
fatal: unable to connect to git.openssl.org:
git.openssl.org[0: 194.97.150.234]: errno=Operation timed out
git.openssl.org[1: 2001:608:c00:180::1:ea]: errno=No route to host

fatal: clone of 'git://git.openssl.org/openssl.git' into submodule path '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl' failed
Failed to clone 'Tor/openssl'. Retry scheduled
Cloning into '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/tor'...
Cloning into '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl'...
fatal: unable to connect to git.openssl.org:
git.openssl.org[0: 194.97.150.234]: errno=Operation timed out
git.openssl.org[1: 2001:608:c00:180::1:ea]: errno=No route to host

fatal: clone of 'git://git.openssl.org/openssl.git' into submodule path '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl' failed
Failed to clone 'Tor/openssl' a second time, aborting
Submodule path 'Extension/tun2tor': checked out '8796fd0fe9fe4c3aee6f48c04cca2f6704ac8236'
Failed to recurse into submodule path 'Carthage/Checkouts/Tor.framework'
Tahers-MBP:iCepa taherismail$ brew install automake autoconf libtool gettext carthage
Warning: automake-1.15 already installed, it's just not linked
Warning: autoconf-2.69 already installed, it's just not linked
Error: Cannot write to /usr/local/Cellar
Tahers-MBP:iCepa taherismail$ carthage build
*** xcodebuild output can be found in /var/folders/jb/2g45vfy53rj_g0fmp5qdstf40000gn/T/carthage-xcodebuild.Xmenz9.log
*** Building scheme "Tor-iOS" in Tor.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	ExternalBuildToolExecution openssl-iOS
(1 failure)
** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution openssl-iOS
(1 failure)
error: can't change directory to '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl' (No such file or directory)
error: can't change directory to '/Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor/openssl' (No such file or directory)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/taherismail/iCepa/Carthage/Checkouts/Tor.framework/Tor.xcodeproj -scheme Tor-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	ExternalBuildToolExecution openssl-iOS
(1 failure)
** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution openssl-iOS
(1 failure)

Tahers-MBP:iCepa taherismail$

**Comment by conradev** [comment]
Hi @Taherismail17, that error is most likely because you don't have access to `openssl.org`, or because their server is not responding.

**Comment by conradev** [comment]
Hi @Taherismail17, going to close this due to inactivity. Feel free to reopen if you have more questions!
