### ISSUE TITLE
Build issue. 2 errors.

### ISSUE THREAD

**Issue by duzvik** [iCepa/iCepa#16]
error: could not find `Cargo.toml` in `/Users/username/Desktop/dev/iCepa/Extension/tun2tor` or any parent directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/aarch64-apple-ios/debug/libtun2tor.a (No such file or directory)

**Comment by jurvis** [comment]
@duzvik did you initialise the submodules?

`git submodule update --init --recursive`

**Comment by duzvik** [comment]
@jurvis  thank you.  it's help.
