### ISSUE TITLE
Error when pressing "Start Tor" button

### ISSUE THREAD

**Issue by duzvik** [iCepa/iCepa#18]
2017-02-02 13:11:05.195483 iCepa[391:42712] <iCepa.ControlViewController: 0x13fd06d10>: Error: Cannot connect to tor: The operation couldn’t be completed. No such file or directory

**Comment by cwoloszynski** [comment]
Looking at the code, it appears that there is an issue in the ControlViewController, line 72:

let cookie = try Data(contentsOf: dataDirectory.appendingPathComponent("control_auth_cookie"), options: NSData.ReadingOptions(rawValue: 0))

I don't see anything in the code that sets a value in the 'control_auth_cookie'. 

I am guessing that I don't know how to configure TOR to use this app.  Can anyone share how to set up the configuration of a device to use TOR?

**Comment by seropunov** [comment]
Me to:
<iCepa.ControlViewController: 0x119d0faa0>: Error: Cannot connect to tor: The operation couldn’t be completed. No such file or directory

**Comment by tladesignz** [comment]
Since I did rework regarding this, I guess, this should not be a problem any more. Therefore I close this, now. Feel free to reopen, if you encounter issues with the latest version.
