### ISSUE TITLE
Failed to connect to git.torproject.org

### ISSUE THREAD

**Issue by holyen** [iCepa/iCepa#23]
it show me errors when run "git submodule update --init --recursive"
how to fix it

**Comment by tladesignz** [comment]
Sorry, no internet connection troubleshooting support here. 
Maybe your provider/country blocks that site or it was just down for a few hours. 

Try using a tunnel software like Tor, Siphon, Shadowsocks or some VPN provider to reach the open internet, in case this problem persists and you have reason to assume, that your country or ISP blocks access to certain sites.
