### ISSUE TITLE
tor: line 57: ./Configure: No such file or directory

### ISSUE THREAD

**Issue by magicsoft** [iCepa/iCepa#24]
line 57: iCepa-master/Carthage/Checkouts/Tor.framework/Tor/openssl.sh:  ./Configure: No such file or directory
make: *** No rule to make target `depend'.  Stop.
make: *** No rule to make target `build_libs'.  Stop.
make: *** No rule to make target `install_dev'.  Stop.
make: *** No rule to make target `distclean'.  Stop.

**Comment by LindyLo** [comment]
Have you followed all instructions in the README ?
It's building fine using Xcode 9.2 (9C40b)

**Comment by magicsoft** [comment]
I fix it! thanks!
