### ISSUE TITLE
build failed with Xcode9

### ISSUE THREAD

**Issue by magicsoft** [iCepa/iCepa#25]
*** Fetching Tor.framework
*** Checking out Tor.framework at "50f357066cedb4c4f4980bae3b027006f2e9973c"
A shell task (/usr/bin/env git clone --quiet https://git.torproject.org/tor.git /Users/zhanmagicpocket/我的软件/Coscos2D/cocosDemo/我的项目/VPN/Demo/iCepa-master/Carthage/Checkouts/Tor.framework/Tor/tor) failed with exit code 128:
fatal: unable to access 'https://git.torproject.org/tor.git/': Failed to connect to git.torproject.org port 443: Connection refused

**Comment by Baccount** [comment]
Can you access https://git.torproject.org/tor.git/  in a non-tor browser?  If not then you’ll probably have to use a VPN.

**Comment by tladesignz** [comment]
It seems, China is blocking Tor's source code repository. Makes sense, from their perspective. Please use Tor, if you already have a running copy or try Psiphon, Shadowsocks or a VPN provider.

I'll close this thread, since this is not an issue of iCepa.
