### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mcginty** [iCepa/iCepa#26]
Firstly, I really appreciate the efforts of iCepa - I'm learning a lot from this code being here and the setup so well-documented. Thank you thank you thank you!

Unfortunately, none of this code can really be used for other projects in iCepa's current state since it's missing a license that would permit any kind of reuse or distribution.

I'm guessing something similar to https://git.zx2c4.com/wireguard-go/tree/README.md#n11 would work, but IANAL nor am I the author.

**Comment by chrisballinger** [comment]
Done!
