### ISSUE TITLE
iCepaTunnel is killed on iPhone 5S for using too much memory

### ISSUE THREAD

**Issue by rl1987** [iCepa/iCepa#28]
Quick investigation (running the app and attaching debugger to iCepaTunnel process) has shown to network extension is killed by iOS for allocating too much memory (17 MB). This happens as soon as I try to open check.torproject.org in Safari.

**Comment by tladesignz** [comment]
Yeah, this is a known issue, currently not resolvable as long as Tor isn't ready. See my blog post about it: https://benjaminerhart.com/2018/03/state-of-the-onion-ios/
