### ISSUE TITLE
Can you provide a binary for self-signing?

### ISSUE THREAD

**Issue by msc-** [iCepa/iCepa#3]
[Kodi](kodi.tv) makes available ios binaries that one can sign with Xcode 7 and install on iOS 9 without needing to sign up as a developer with Apple. See http://kodi.wiki/view/HOW-TO:Install_Kodi_for_iOS (near the bottom of the page) and http://dantheman827.github.io/ios-app-signer/.

Any chance this project could do the same thing? It seems building from source is quite some chore. Making binaries would enable more people to install and test the software.

**Comment by msc-** [comment]
It looks like you need to be an Apple developer (US $99 / year) to get access to the Network Extension framework so binaries won't help as many people as I thought.

**Comment by conradev** [comment]
Yes, unfortunately you need to request permission on top of a paid Apple Developer account, so it's neither free nor straightforward to self-sign.

When the project is functional, it will be on the App Store!

**Comment by msc-** [comment]
> When the project is functional, it will be on the App Store!

Yes I was expecting that. My suggestion was only to help increase the pool of testers.

There doesn't seem to be much progress. The last commit was 3 months ago. Is there any timeframe for completion? It is really frustrating not to be able to get those nice Guardian Project apps for iOS.

**Comment by FredericJacobs** [comment]
Note: This project is not affiliated with the Guardian Project.
