### ISSUE TITLE
Build Failed (Carthage)

### ISSUE THREAD

**Issue by MrBenFTW** [iCepa/iCepa#31]
Cathage fails to build so i assumed is was to do with the simulator, so i ignored it and tried to run in xcode and i get a `'Tor/Tor.h' file not found`

Cathage:

Bens-MacBook-Pro:iCepa mrbenftw$ carthage build --platform iOS
*** xcodebuild output can be found in /var/folders/mz/1cg7sr7s7b515769b36sv9w40000gn/T/carthage-xcodebuild.nbZ1Yl.log
*** Building scheme "Tor-iOS" in Tor.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mrbenftw/Desktop/VPN/iCepa/Carthage/Checkouts/Tor.framework/Tor.xcodeproj -scheme Tor-iOS -configuration Release -derivedDataPath /Users/mrbenftw/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/Tor.framework/f55ed743cad916d0746ffb53eb3d174500d5477d -sdk iphonesimulator -destination platform=iOS\ Simulator,id=C9D7D128-DD91-42A9-A913-CCBBEB2D088A -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/mrbenftw/Desktop/VPN/iCepa/Carthage/Checkouts/Tor.framework)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mz/1cg7sr7s7b515769b36sv9w40000gn/T/carthage-xcodebuild.nbZ1Yl.log
Bens-MacBook-Pro:iCepa mrbenftw$

**Comment by tladesignz** [comment]
1. iCepa **will not run in the simulator**.
2. The important information is in the mentioned ```carthage-xcodebuild.nbZ1Yl.log```. There's no way to debug this without the information in there.
3. It seems that iCepa references Tor.framework's latest master commit. That's suboptimal, I'm sorry. Mike did the latest updates to that, so I'm not up to date on any issues with it. Currently, I can only vouch for my latest commits from May. Try to checkout these, and see how it works with these.
4. Do you use the latest Xcode? Could be, that there are issues.
5. Be sure to read my article about the state of Tor on iOS: It's mostly about iCepa: https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

I will be back to this next year (which isn't long, considering it's mid-November...). Until then, you're basically on your own, sorry! ¯\_(ツ)_/¯
