### ISSUE TITLE
Build falied

### ISSUE THREAD

**Issue by Ahmedbutt** [iCepa/iCepa#32]
I am trying to build the project for iOS but it is saying that you done have archtecture for arm64. Error is as follows:

<img width="707" alt="Screen Shot 2019-08-06 at 3 38 37 PM" src="https://user-images.githubusercontent.com/5628406/62571858-67d69c80-b860-11e9-9f5a-b36936493c1e.png">

**Comment by tladesignz** [comment]
That's in libtun2tor, a component written in Rust.
Looks like you didn't install all Rust targets.

Make sure to follow the instructions about how to install Rust properly from here:

https://github.com/iCepa/iCepa/blob/master/README.md

**Comment by Ahmedbutt** [comment]
<img width="537" alt="Screen Shot 2019-08-06 at 4 42 48 PM" src="https://user-images.githubusercontent.com/5628406/62575682-4a5a0080-b869-11e9-8c87-9073b640c0b9.png">

**Comment by FaisalRGoraya** [comment]
Any Guide about this?
