### ISSUE TITLE
What is serverAddress in NETunnelProviderProtocol confuguration?

### ISSUE THREAD

**Issue by simform-solutions** [iCepa/iCepa#36]
Hello,
I found `config.serverAddress = "somebridge" ` in the permissionViewController.swift file.
I added the server address "127.0.0.1" there. But it disconnected. Can you please guide me what server address I need to put there to connect TOR-VPN.
Thank you!

**Comment by tladesignz** [comment]
You might want to have a look at my attempt at restarting that project:

https://github.com/tladesignz/iCepa/tree/restart

It isn't working, yet, because of lacking DNS support, that's why I didn't move it to this repo, yet.

**Comment by simform-solutions** [comment]
Hi Benjamin,
Thanks for your update.
Appreciated your work towards TOR!!
I just want to know that`TorController(socketHost: "127.0.0.1", port: 9050)` will create TOR controller in the packetTunnelProvider class. But, When I try to connect this TorController, it gives me this error. `Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"`
Do you have any idea about it?

**Comment by tladesignz** [comment]
> I just want to know that`TorController(socketHost: "127.0.0.1", port: 9050)` will create TOR controller in the packetTunnelProvider class. But, When I try to connect this TorController, it gives me this error. `Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"`

The host and port you give `TorController` needs to be the address, Tor is listening on (typically localhost) and the configured control port. The control port is where you talk to Tor to change its configuration.

So, you need to first start Tor and configure it correctly. Then wait a little (less than a second will be enough), then start the `TorController`.

When that's successful, you can query the `TorController` for Tor's status and change its configuration.

See

https://github.com/tladesignz/iCepa/blob/21e3c75512376f66ff3f7e535a060767782e2c6a/TorVPN/BasePTProvider.swift#L41-L48

https://github.com/tladesignz/iCepa/blob/21e3c75512376f66ff3f7e535a060767782e2c6a/TorVPN/BasePTProvider.swift#L144

https://github.com/tladesignz/iCepa/blob/21e3c75512376f66ff3f7e535a060767782e2c6a/TorVPN/BasePTProvider.swift#L152

https://github.com/tladesignz/iCepa/blob/21e3c75512376f66ff3f7e535a060767782e2c6a/TorVPN/BasePTProvider.swift#L185-L187

**Comment by tladesignz** [comment]
To be honest: This is not a Tor support forum. If you have difficulty understanding the different concepts of Tor, I very much recommend reading all about Tor on their page: https://2019.www.torproject.org/docs/documentation.html.en
