### ISSUE TITLE
Cannot access .onion URL

### ISSUE THREAD

**Issue by umangoo** [iCepa/iCepa#40]
Hi,
The project is already running.
Successfully visited Host: https://check.torproject.org
But cannot visit Host: https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/
How can I solve this problem?
Thank you

**Comment by tladesignz** [comment]
Working on it: 71925221a606c94cdd1ba76df270ce59be5ad350

Unfortunately, not fully working, yet. That commit makes the OS resolve the .onion address, and trigger the request, but it still times out, although Tor is heavily working.

Not sure why, yet. Your help is appreciated!

**Comment by tladesignz** [comment]
Ok, got it.
