### ISSUE TITLE
Release build broken

### ISSUE THREAD

**Issue by DoDoENT** [iCepa/iCepa#42]
Release build fails with 
```
Ld /Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Products/Release-iphoneos/Tor.framework/Tor normal (in target 'Tor-iOS' from project 'Tor')
    cd /Users/dodo/Work/CloneOuts/iCepa/Tor.framework
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -L/Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Products/Release-iphoneos -F/Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Products/Release-iphoneos -filelist /Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Intermediates.noindex/Tor.build/Release-iphoneos/Tor-iOS.build/Objects-normal/arm64/Tor.LinkFileList -install_name @rpath/Tor.framework/Tor -Xlinker -rpath -Xlinker @loader_path/.. -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -object_path_lto -Xlinker /Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Intermediates.noindex/Tor.build/Release-iphoneos/Tor-iOS.build/Objects-normal/arm64/Tor_lto.o -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -fapplication-extension -ltor -lssl -lcrypto -levent -levent_core -levent_extra -levent_pthreads -llzma -lz -Xlinker -dependency_info -Xlinker /Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Intermediates.noindex/Tor.build/Release-iphoneos/Tor-iOS.build/Objects-normal/arm64/Tor_dependency_info.dat -o /Users/dodo/Library/Developer/Xcode/DerivedData/iCepa-cjffkldphkgpqraghzyrjxmzcvrs/Build/Products/Release-iphoneos/Tor.framework/Tor

ld: library not found for -ltor
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Debug build works OK.

Also, the build instructions in the README don't mention that you also need to install Rust, cbindgen and ffi. Also, if using M1 Macs, `tor.sh`, `xz.sh` and `libevent.sh` needs to be modified and `/usr/local/...` changed to `/opt/homebrew/...`.

**Comment by mubashar1199** [comment]
Hello, i need some information, sorry i am writing this here.
I want to create instant messaging app via sockets using tor network, can it be possible using this library?  Does it provide .onion address and accept connection on that address and is it able to connect to other’s .onion address?
I am making it for both android and ios, its working for android, can i do this on IOS?

**Comment by tladesignz** [comment]
> Hello, i need some information, sorry i am writing this here.
> 
> I want to create instant messaging app via sockets using tor network, can it be possible using this library?  Does it provide .onion address and accept connection on that address and is it able to connect to other’s .onion address?
> 
> I am making it for both android and ios, its working for android, can i do this on IOS?

What you need is https://github.com/iCepa/Tor.framework

See OnionShare iOS source code on how to create an onion service.

**Comment by tladesignz** [comment]
> Also, the build instructions in the README don't mention that you also need to install Rust, cbindgen and ffi. Also, if using M1 Macs, `tor.sh`, `xz.sh` and `libevent.sh` needs to be modified and `/usr/local/...` changed to `/opt/homebrew/...`.

There's now a pure Cocoapod version of Tor.framework which builds on M1 Macs.
