### ISSUE TITLE
Building the project fails

### ISSUE THREAD

**Issue by ali-ht10** [iCepa/iCepa#5]
I tried building the project but it fails with these errors:
- iCepa-master/iOS/ViewController.swift:21:9: Type 'NETunnelProviderManager' has no member 'loadOrCreateDefaultWithCompletionHandler'
- could not find `Cargo.toml` in `iCepa-master/Extension/tun2tor` or any parent directory
  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/x86_64-apple-ios/debug/libtun2tor.a (No such file or directory)

I have followed the exact steps mentioned in README.

**Comment by conradev** [comment]
- I forgot to push a file – check now and see if the `ViewController` builds
- Can you post the full build log of `tun2tor-iOS`?

Also, Rust is now at version 1.8, so you might want to follow the updated README instructions.

Also, of note: you will not be able to use iCepa at all unless you have those entitlements from Apple.

**Comment by ali-ht10** [comment]
ViewController builds now. I have followed the updated README but the error is there.
Here is the full build log of tun2tor-iOS
https://gist.github.com/ali-ht10/32b8c46c24004895c3971e3d4fc17ac7

**Comment by conradev** [comment]
Make sure that your submodules are initialized:
```
git submodule update --init --recursive
```

**Comment by ali-ht10** [comment]
Submodules not being initialized is causing the tun2tor-iOS issue?

**Comment by conradev** [comment]
That's the only reason I can think of that `Cargo.toml` would not be in `Extension/tun2tor`. Is the file there?

**Comment by ali-ht10** [comment]
Nop

**Comment by ali-ht10** [comment]
But I don't think the second error, Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/x86_64-apple-ios/debug/libtun2tor.a ,
is related to Cargo.toml. Maybe its not building the tun2tor.sh file.

**Comment by ali-ht10** [comment]
Well I initialized the submodules and **Cargo.toml** was there after the initialization. Missing **Cargo.toml** error is fixed. On building the project, I get this:
Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling ip v1.1.1
   Compiling libc v0.2.10
   Compiling socks v0.1.0 (file:///Workspace/Documents/iCepa/iCepa/Extension/tun2tor)
   Compiling tun2tor v0.1.0 (file:///Workspace/Documents/iCepa/iCepa/Extension/tun2tor)
error: could not find native static library `compiler-rt`, perhaps an -L flag is missing?
Could not compile `tun2tor`.

To learn more, run the command again with --verbose.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: target/x86_64-apple-ios/debug/libtun2tor.a (No such file or directory)

Here is the full build log:
https://gist.github.com/ali-ht10/ca5721736cae71e951213ca60cbca4f0

**Comment by ali-ht10** [comment]
After reinstalling rust, I did manage to successfully build the project. But when I press **Start Tor** button, the **controller.addObserverForCircuitEstablished** block is never called. The **connected** property of controller was **false**.

**Comment by conradev** [comment]
To respond to your old comments:
- The second error, `can't open input file` was a result of the failure of the first error
- Not being able to find `compiler-rt` is most likely because the compiler does not have the proper target compiled in

As for `NSPOSIXErrorDomain Code=49`, or `EADDRNOTAVAIL` – that is a current crippling issue that was introduced by some change I made and I can't figure out what causes it or how to fix it. That is what I am currently working on with regards to the project. I will try to fix it this weekend!

**Comment by ali-ht10** [comment]
And what about the Tor configuration and the TunnelNetworkSettings?

**Comment by ali-ht10** [comment]
I'm just wondering that whether Apple allows you to route all of your device's traffic through Tor. Because on App Store, majority of the apps related to Tor are Web Browsers. Meaning only one app's traffic is routed through Tor. I did query this question about whether Apple allows you to route all your traffic but got no response.

What do you think?

**Comment by mtigas** [comment]
Hi @ali-ht10, you’re correct that apps currently in the App Store only have Tor within themselves. Generally, if you want Tor inside an iOS app, the Tor daemon needs be run as a thread within the app — not as a subprocess, like on Android or on normal computers. When you leave the Tor-using app to use another app, the Tor daemon is paused along with the rest of the app and can no longer process traffic.

The entire point of this iCepa project _is_ to build something where Tor can run system-wide, as you describe. (The [iOS 9 Network Extension framework](https://developer.apple.com/library/ios/documentation/NetworkExtension/Reference/Network_Extension_Framework_Reference/) is the new thing that hopefully allows this to happen.) However, iCepa is still a work in progress and does not completely work yet (see [list here](https://github.com/iCepa/iCepa#contributing)). So some of your other questions may not have answers yet.

But: the default `NEPacketTunnelNetworkSettings` and `TORConfiguration()` options should be OK to reuse, though if Tor is blocked where you are located, you may need more settings passed to `TORConfiguration()`.

(I’m going to leave this ticket open pending the `NSPOSIXErrorDomain Code=49 "Can't assign requested address"` issue.)

**Comment by Alekseykua** [comment]
Is this project still active? Interested in participating.

**Comment by conradev** [comment]
Yes it is! I am going to push some changes with Swift 3 in `iCepa` and `Tor.framework`, and it should be possible to develop without a jailbreak now that iOS 10 beta 2 raises the memory limit!

**Comment by Alekseykua** [comment]
Requested "special Network Extension entitlements". Looking forward to getting this app live !

**Comment by Alekseykua** [comment]
Looks like i need a payed developer account 👎

**Comment by conradev** [comment]
I resolved `EADDRNOTAVAIL` back in June at WWDC – going to close this issue.
