### ISSUE TITLE
How is the project coming along?

### ISSUE THREAD

**Issue by BobsUncle** [iCepa/iCepa#6]
Been waiting along time to see this app come into the mainstream.... whats the current situation? Any chance we can expect to see it soon for general use?

**Comment by chrisballinger** [comment]
Unfortunately the main blocker is the 5 MB RAM limit for packet provider extensions.

**Comment by s1lvester** [comment]
And I guess you're not counting on apple to come to the rescue... But who knows. WWDC is just around the corner :smirk:
