### ISSUE TITLE
Project Updates w/ iOS10

### ISSUE THREAD

**Issue by BobsUncle** [iCepa/iCepa#7]
With the recent beta of iOS 10 v2 increasing the memory limit to 15 MB... does that mean the bottleneck has been removed and development is going forward?

**Comment by conradev** [comment]
Yes! It's blocked on me, and I will be allocating more time to work on this. My time right now is split between [Workflow](https://workflow.is) and [VotePlz](https://www.voteplz.org).

**Comment by BobsUncle** [comment]
Thanks Conrad. Your effort is truly appreciated :) thank you

**Comment by Alekseykua** [comment]
Conrad, Voteplz is amazing!
